apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: full-chain
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    enabled: false
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - mountPath: /flag
                name: flag
                readOnly: true
        volumes:
          - name: flag
            secret:
              defaultMode: 0555
              secretName: full-chain-flag
              optional: true
