version: "3.7"
services:
  ormlogin-nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    restart: always
    depends_on:
      - "ormlogin-fpm"
    ports:
      - "2150:8080"
  ormlogin-fpm:
    build:
      context: .
      dockerfile: fpm.dockerfile
    restart: always
    user: www-data
    security_opt:
      - no-new-privileges
    deploy:
      resources:
        limits:
          memory: 200M
    read_only: true