[auteur]
pseudo =  "Nics" # Sera affiché sur l'interface publique
[challenge]
nom = "LPN - Active"
points = 100
decription = "You found a tag in the parking lot. It grants access to a better parking spot than yours. It's hard to directly read the secret from its memory but you know the protocol used (`tag.py`). Why don't you try an active attack to retrieve the secret? You can interact with the tag using `nc TODO TODO`" # default port : 4361
flag = "GH19{Trivial_active_attacks_:'(}"
categorie = "Crypto"

