version: '3'
services:
 web:
  build: ./server
  env_file :
   - ./.env
  depends_on:
   - "${MYSQL_HOST}"
  ports:
   - 80:31337
  restart: always

 db:
  build: ./database
  command: --default-authentication-plugin=mysql_native_password
  env_file :
   - ./.env
  ports:
   - 3306:3306

